import Foundation

// swiftlint:disable:next missing_docs
public enum SafetyNET {

  /**
   The MSI Status field, which confirms whether the entire Marine Safety
   Information (MSI) message has been correctly and completely received by the
   EGC Terminal. Used by the `SM1`, `SM2`, `SM3`, and `SM4` sentences (field 1,
   section 8.3.92 comment 1).

   - SeeAlso: ``Message/Payload-swift.enum``
   */
  public enum MSIStatus: String, Sendable, Codable, Equatable {

    /// `A`: MSI Message complete – all data fields in this sentence and the
    /// associated `SMB` sentences are complete and valid.
    case complete = "A"

    /// `V`: MSI Message not complete – some data fields may be null or in an
    /// unknown state, or some characters within the MSI message body in the
    /// associated `SMB` sentences may be represented by the underscore `_`
    /// character.
    case incomplete = "V"
  }

  /**
   Ocean region code identifying the Inmarsat satellite ocean region that
   relayed the MSI message. Used by the `SM1`, `SM2`, `SM3`, and `SM4`
   sentences (field 5, section 8.3.92 comment 5). This field is never null.

   - SeeAlso: ``Message/Payload-swift.enum``
   */
  public enum OceanRegion: Int, Sendable, Codable, Equatable {

    /// `0`: Atlantic Ocean Region – West
    case atlanticWest = 0

    /// `1`: Atlantic Ocean Region – East
    case atlanticEast = 1

    /// `2`: Pacific Ocean Region
    case pacific = 2

    /// `3`: Indian Ocean Region
    case indian = 3

    /// `8`: Unknown
    case unknown = 8

    /// `9`: All ocean regions
    case all = 9
  }

  /**
   Priority code of the MSI message. Used by the `SM1`, `SM2`, `SM3`, and `SM4`
   sentences (field 6, section 8.3.92 comment 6). This field is never null.

   - SeeAlso: ``Message/Payload-swift.enum``
   */
  public enum Priority: Int, Sendable, Codable, Equatable {

    /// `1`: Safety
    case safety = 1

    /// `2`: Urgency
    case urgency = 2

    /// `3`: Distress
    case distress = 3

    /// `9`: Unknown
    case unknown = 9
  }

  /**
   Presentation code: a fixed two-digit numeric value that defines the language
   to be used for presentation of the MSI message. Used by the `SM1`, `SM2`,
   `SM3`, and `SM4` sentences (field 8, section 8.3.92 comment 8).

   - SeeAlso: ``Message/Payload-swift.enum``
   */
  public enum PresentationCode: Int, Sendable, Codable, Equatable {

    /// `00`: International Alphabet Number 5
    case internationalAlphabet5 = 0
  }

  /**
   Identification of the source and sequence of an MSI message, shared by the
   `SM1`, `SM2`, `SM3`, and `SM4` sentences (fields 2, 3, and 4; section 8.3.92
   comments 2, 3, and 4). The ``uniqueMessageNumber`` also appears alone in the
   `SMB` and `SMV` sentences and is the value that links those sentences back to
   their originating `SM1`–`SM4` sentence.

   - SeeAlso: ``Message/Payload-swift.enum``
   */
  public struct MessageIdentification: Sendable, Codable, Equatable {

    /// The Unique Message Number generated by the receiving EGC Terminal
    /// (Mobile/Ship Earth Station). A variable-length integer, maximum 6
    /// digits. Never null. The same value appears in the associated `SMB` and
    /// `SMV` sentences and links them to this message.
    public let uniqueMessageNumber: UInt

    /// The Unique Message Sequence Number assigned by the originating Land
    /// Earth Station (LES). Six fixed digits (zero-filled). `nil` if any
    /// portion was received in error or is unknown to the EGC Terminal.
    public let lesSequenceNumber: UInt?

    /// The 3-digit numeric ID of the LES that originated the MSI message.
    /// `nil` if any portion was received in error or is unknown to the EGC
    /// Terminal.
    public let lesID: UInt?

    /**
     Creates a message identification record.

     - Parameter uniqueMessageNumber: The Unique Message Number generated by the
     receiving EGC Terminal.
     - Parameter lesSequenceNumber: The LES-assigned Unique Message Sequence
     Number, or `nil` if unknown.
     - Parameter lesID: The 3-digit LES ID, or `nil` if unknown.
     */
    public init(uniqueMessageNumber: UInt, lesSequenceNumber: UInt?, lesID: UInt?) {
      self.uniqueMessageNumber = uniqueMessageNumber
      self.lesSequenceNumber = lesSequenceNumber
      self.lesID = lesID
    }

    /// Parses the shared SafetyNET identification fields (unique message number,
    /// LES sequence number, LES ID) from a sentence, applying the common range
    /// and sign validation used by the SM1-SM4 sentences.
    init(
      fields: Fields,
      uniqueIndex: Int,
      lesSequenceIndex: Int,
      lesIDIndex: Int
    ) throws {
      let uniqueValue = try fields.int(at: uniqueIndex)!
      guard (0...999_999).contains(uniqueValue) else {
        throw fields.fieldError(type: .badNumericValue, index: uniqueIndex)
      }
      let lesSequence = try fields.int(at: lesSequenceIndex, optional: true).map { value -> UInt in
        guard let unsigned = UInt(exactly: value) else {
          throw fields.fieldError(type: .badNumericValue, index: lesSequenceIndex)
        }
        return unsigned
      }
      let lesID = try fields.int(at: lesIDIndex, optional: true).map { value -> UInt in
        guard let unsigned = UInt(exactly: value) else {
          throw fields.fieldError(type: .badNumericValue, index: lesIDIndex)
        }
        return unsigned
      }
      self.init(
        uniqueMessageNumber: UInt(uniqueValue),
        lesSequenceNumber: lesSequence,
        lesID: lesID
      )
    }
  }
}
